using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rebus.AdoNet.Dialects
{
	public class PostgreSql10Dialect : PostgreSql95Dialect
	{
		private readonly TypeNames _typeNames = new TypeNames();
		protected override Version MinimumDatabaseVersion => new Version("10");

		public override bool SupportsTryAdvisoryXactLockFunction => true;
		public override ushort Priority => 100;

		public override bool SupportsThisDialect(IDbConnection connection)
		{
			try
			{
				var versionString = (string)connection.ExecuteScalar(@"SELECT VERSION();");
				var databaseVersion = new Version(this.GetDatabaseVersion(connection));
				return versionString.StartsWith("PostgreSQL ") && databaseVersion >= MinimumDatabaseVersion;
			}
			catch
			{
				return false;
			}
		}

		public override string GetIdentityTypeFor(DbType type)
		{
			return string.Format("{0} GENERATED BY DEFAULT AS IDENTITY", _typeNames.Get(type));
		}
	}
}
