using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rebus.AdoNet.Dialects
{
	public class PostgreSql10Dialect : PostgreSql95Dialect
	{
		protected override Version MinimumDatabaseVersion => new Version("10.0");
		private Version MinimumDatabaseVersion => new Version("10");
		protected override Version MinimumDatabaseVersion => new Version("10");
		public override ushort Priority => 100;

		public override bool SupportsTryAdvisoryXactLockFunction => true;

		public override string GetIdentityTypeFor(DbType type)
		{
			return string.Format("{0} GENERATED BY DEFAULT AS IDENTITY", GetColumnType(type));
		}
	}
}
